package frc.robot.subsystems.IntakeSubsystem;

import static edu.wpi.first.units.Units.Degrees;

import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.measure.Angle;

/**
 * Constants for swerve drive subsystem.
 * Generated by Thrifty Swerve Generator.
 * Generated on: 2025-07-17T22:32:29.693Z
 */
public final class IntakeConstants {
    
}